'''try:
    x = int(input("Ingresa un número: "))
    y = 1 / x
    print(y)
except ZeroDivisionError:
    print("No puedes dividir entre cero, lo siento.")
except ValueError:
    print("Debes ingresar un valor entero..")
except:
    print("Oh cielos, algo salió mal...")

print("FIN.")'''


#assert cuando se devuelve alguno de estos valores genera la exception AssertionError
#assert ''
#assert 0
#assert None
#assert False

def fun(entrada,limiteS,limiteI):
    while True:
        try:
            while True:
                if  entrada < limiteI or entrada > limiteS:
                    print("Error: El Valor no esta dentro del rango permitido entre "+str(limiteI)+' '+'y ' + str(limiteS))
                    entrada=int(input("Debe ingresar un valor dentro del rango: "))
                    continue
                else: break
            break
        except TypeError:
            print("Dato invalido")
            continue
    return entrada 

while True:
    try:    
        limI=int(input("Ingrese Valor Minimo: "))
    except:
        print("Ingrese un valor numerico entero")
        continue
    break

while True:
    try:
        limS=int(input("Ingrese Valor Superior: "))
    except:
        print("Ingrese un valor numerico entero")
        continue
    break

while True:    
    try:        
        valor=int(input("Ingrese Valor: "))
    except:
        print("Ingrese un valor numerico entero")
        continue
    break
print("Numero Ingresado fue: ",fun(valor,limS,limI))
    
    
    





